# Change these first
owner: ISAIC-ca # Your GitHub organization or username, where this repository lives
repo: uptime-status # The name of this repository

sites:
  - name: VMondemand
    url: https://vmod.isaic.ca/app/authentication/sign-in
  - name: ISAIC Website
    url: https://isaic.ca
  - name: Openstack Infrastructure
    url: https://aihubdb.ece.ualberta.ca/auth/login/?next=/
    __dangerous__insecure: true
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ISAIC Uptime Status
  introTitle: "**ISAIC** Services Status"
  introMessage: This page displays the status of the services ISAIC provides. 
  navbar:
    - title: ISAIC Website
      href: https://www.isaic.ca
    - title: VMondemand
      href: https://vmod.isaic.ca/app/authentication/sign-in

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
